require('packer-plugins')
require('treesitter-config')
require('nvim-tree-config')
require('bufferline-config')
require('nvim-tree-config')
require('telescope-config')
require('keybindings')
require('options')
require('lsp-config')
vim.cmd('colorscheme rose-pine')
-- vim.cmd[[:colorscheme jellybean]]
-- require('completion_setup')
